-- Story 2: the default spaces and checklists every household starts with.
-- Source: PRD Checklists tab. `position` is each item's order within its list.

create type public.cadence as enum ('weekly', 'monthly', 'seasonal');

create table public.space_templates (
  position int primary key,
  name text not null unique,
  template_key text not null
);

create table public.checklist_templates (
  id serial primary key,
  template_key text not null,
  cadence public.cadence not null,
  position int not null check (position > 0),
  label text not null,
  unique (template_key, cadence, position)
);

-- Templates are only read by security definer functions; no API access.
alter table public.space_templates enable row level security;
alter table public.checklist_templates enable row level security;

insert into public.space_templates (position, name, template_key) values
  (1, 'Kitchen', 'kitchen'),
  (2, 'Bathroom 1', 'bathroom'),
  (3, 'Bathroom 2', 'bathroom'),
  (4, 'Living Room', 'living_room'),
  (5, 'Dining Room', 'dining_room'),
  (6, 'Stairs', 'stairs'),
  (7, 'Hallways', 'hallways');

insert into public.checklist_templates (template_key, cadence, position, label) values
  ('kitchen', 'weekly', 1, 'Wipe and disinfect the countertops'),
  ('kitchen', 'weekly', 2, 'Scrub and disinfect the sink'),
  ('kitchen', 'weekly', 3, 'Scrub and deodorize the sink drain / garbage disposal'),
  ('kitchen', 'weekly', 4, 'Clean the stovetop surface grates and knobs'),
  ('kitchen', 'weekly', 5, 'Clean the microwave inside and out'),
  ('kitchen', 'weekly', 6, 'Wipe small appliances (toaster, kettle, coffee maker)'),
  ('kitchen', 'weekly', 7, 'Empty and clean the toaster crumb tray'),
  ('kitchen', 'weekly', 8, 'Wipe cabinet fronts and handles'),
  ('kitchen', 'weekly', 9, 'Wipe the fridge exterior and handles'),
  ('kitchen', 'weekly', 10, 'Disinfect high-touch spots (handles, switches)'),
  ('kitchen', 'weekly', 11, 'Take out the trash and recycling'),
  ('kitchen', 'weekly', 12, 'Wipe the trash can lid and exterior'),
  ('kitchen', 'weekly', 13, 'Launder dish towels cloths and oven mitts'),
  ('kitchen', 'weekly', 14, 'Sweep the floor'),
  ('kitchen', 'weekly', 15, 'Mop the floor'),
  ('kitchen', 'monthly', 1, 'Deep clean the oven'),
  ('kitchen', 'monthly', 2, 'Clean the range hood filter and vent'),
  ('kitchen', 'monthly', 3, 'Wipe inside fridge shelves and drawers'),
  ('kitchen', 'monthly', 4, 'Check for and toss expired food and pantry items'),
  ('kitchen', 'monthly', 5, 'Descale the kettle and coffee maker'),
  ('kitchen', 'monthly', 6, 'Clean the dishwasher filter and run a cleaning cycle'),
  ('kitchen', 'monthly', 7, 'Dust the tops of the fridge and cabinets'),
  ('kitchen', 'monthly', 8, 'Clean under and behind small appliances'),
  ('kitchen', 'seasonal', 1, 'Pull out the fridge and stove; clean behind and underneath'),
  ('kitchen', 'seasonal', 2, 'Defrost the freezer if needed'),
  ('kitchen', 'seasonal', 3, 'Empty wipe and reorganize the pantry'),
  ('kitchen', 'seasonal', 4, 'Wash windows and window sills'),
  ('kitchen', 'seasonal', 5, 'Clean light fixtures and replace bulbs as needed'),
  ('kitchen', 'seasonal', 6, 'Deep clean floor edges and grout'),
  ('kitchen', 'seasonal', 7, 'Replace the fridge water filter / baking soda box'),
  ('bathroom', 'weekly', 1, 'Scrub and disinfect the toilet (bowl, seat, lid, base, handle)'),
  ('bathroom', 'weekly', 2, 'Clean and disinfect the sink and counter'),
  ('bathroom', 'weekly', 3, 'Clean the mirror'),
  ('bathroom', 'weekly', 4, 'Scrub the shower / tub walls and floor'),
  ('bathroom', 'weekly', 5, 'Clean the shower door or rinse the curtain liner'),
  ('bathroom', 'weekly', 6, 'Wipe and shine faucets handles and fixtures'),
  ('bathroom', 'weekly', 7, 'Disinfect high-touch spots (switch, door handle, flush handle)'),
  ('bathroom', 'weekly', 8, 'Empty and wipe out the trash can'),
  ('bathroom', 'weekly', 9, 'Sweep and mop / disinfect the floor'),
  ('bathroom', 'weekly', 10, 'Launder bath mats and hand towels'),
  ('bathroom', 'weekly', 11, 'Refill soap toilet paper and supplies'),
  ('bathroom', 'monthly', 1, 'Descale the showerhead and faucets (vinegar soak)'),
  ('bathroom', 'monthly', 2, 'Clean grout and spot-treat mold and mildew'),
  ('bathroom', 'monthly', 3, 'Wash or replace the shower curtain liner'),
  ('bathroom', 'monthly', 4, 'Wipe cabinet fronts and clean drawers'),
  ('bathroom', 'monthly', 5, 'Clean and organize under-sink storage'),
  ('bathroom', 'monthly', 6, 'Dust vents the exhaust fan cover and light fixtures'),
  ('bathroom', 'monthly', 7, 'Wipe baseboards and behind the toilet'),
  ('bathroom', 'monthly', 8, 'Clean and deodorize the drains'),
  ('bathroom', 'seasonal', 1, 'Reseal or replace caulk lines as needed'),
  ('bathroom', 'seasonal', 2, 'Deep scrub tile and grout'),
  ('bathroom', 'seasonal', 3, 'Wash the window and window sill'),
  ('bathroom', 'seasonal', 4, 'Clean inside the exhaust fan'),
  ('bathroom', 'seasonal', 5, 'Descale and deep clean the toilet tank'),
  ('bathroom', 'seasonal', 6, 'Wash or replace the shower curtain; clean the rod and rings'),
  ('living_room', 'weekly', 1, 'Dust all surfaces (tables, shelves, TV stand, electronics)'),
  ('living_room', 'weekly', 2, 'Clean the TV screen with a microfiber cloth'),
  ('living_room', 'weekly', 3, 'Vacuum the carpet rug and floor'),
  ('living_room', 'weekly', 4, 'Vacuum couch cushions and underneath them'),
  ('living_room', 'weekly', 5, 'Mop hard floors'),
  ('living_room', 'weekly', 6, 'Wipe the coffee table and side tables'),
  ('living_room', 'weekly', 7, 'Tidy books magazines and cables'),
  ('living_room', 'weekly', 8, 'Empty the trash'),
  ('living_room', 'weekly', 9, 'Disinfect remotes and light switches'),
  ('living_room', 'monthly', 1, 'Dust baseboards vents and window sills'),
  ('living_room', 'monthly', 2, 'Wipe down and organize the media console and cables'),
  ('living_room', 'monthly', 3, 'Vacuum under the furniture'),
  ('living_room', 'monthly', 4, 'Dust the ceiling fan and light fixtures'),
  ('living_room', 'monthly', 5, 'Spot-clean walls doors and switch plates'),
  ('living_room', 'monthly', 6, 'Fluff and rotate cushions; clean under them'),
  ('living_room', 'monthly', 7, 'Dust decor frames lamps and shades'),
  ('living_room', 'seasonal', 1, 'Wash windows curtains and blinds'),
  ('living_room', 'seasonal', 2, 'Shampoo or deep clean the carpet or rug'),
  ('living_room', 'seasonal', 3, 'Deep clean upholstery (couch and chairs)'),
  ('living_room', 'seasonal', 4, 'Move furniture and clean beneath'),
  ('living_room', 'seasonal', 5, 'Wash throw blankets and pillow covers'),
  ('living_room', 'seasonal', 6, 'Clean or replace HVAC vent covers / filters'),
  ('dining_room', 'weekly', 1, 'Dust the table chairs and surfaces'),
  ('dining_room', 'weekly', 2, 'Wipe chair seats and backs'),
  ('dining_room', 'weekly', 3, 'Clean placemats and wipe the table runner'),
  ('dining_room', 'weekly', 4, 'Vacuum or sweep and mop the floor'),
  ('dining_room', 'weekly', 5, 'Dust the light fixture / chandelier (reachable parts)'),
  ('dining_room', 'weekly', 6, 'Wipe down any buffet hutch or cabinet surfaces'),
  ('dining_room', 'weekly', 7, 'Tidy and wipe shelving and decor'),
  ('dining_room', 'weekly', 8, 'Empty the trash if there is a bin'),
  ('dining_room', 'monthly', 1, 'Dust baseboards and window sills'),
  ('dining_room', 'monthly', 2, 'Polish wood furniture (if applicable)'),
  ('dining_room', 'monthly', 3, 'Vacuum the rug thoroughly and clean underneath'),
  ('dining_room', 'monthly', 4, 'Spot-clean walls and scuff marks'),
  ('dining_room', 'monthly', 5, 'Launder table linens and napkins'),
  ('dining_room', 'monthly', 6, 'Dust picture frames and decor'),
  ('dining_room', 'seasonal', 1, 'Wash windows curtains and blinds'),
  ('dining_room', 'seasonal', 2, 'Deep clean upholstered chairs'),
  ('dining_room', 'seasonal', 3, 'Thoroughly clean light fixtures'),
  ('dining_room', 'seasonal', 4, 'Move furniture and clean underneath'),
  ('dining_room', 'seasonal', 5, 'Deep clean or rotate the rug'),
  ('stairs', 'weekly', 1, 'Vacuum each step including edges and corners'),
  ('stairs', 'weekly', 2, 'Vacuum the stair runner'),
  ('stairs', 'weekly', 3, 'Wipe and disinfect the handrail and banister'),
  ('stairs', 'weekly', 4, 'Dust the balusters / spindles'),
  ('stairs', 'weekly', 5, 'Spot-clean walls along the staircase'),
  ('stairs', 'weekly', 6, 'Sweep or vacuum the landing(s)'),
  ('stairs', 'monthly', 1, 'Dust baseboards and trim along the stairs'),
  ('stairs', 'monthly', 2, 'Wipe wall scuffs and switch plates'),
  ('stairs', 'monthly', 3, 'Dust wall art and photos in the stairwell'),
  ('stairs', 'monthly', 4, 'Clean the stairwell light fixture (reachable)'),
  ('stairs', 'monthly', 5, 'Vacuum under the runner edges'),
  ('stairs', 'seasonal', 1, 'Deep clean or shampoo the stair runner / carpet'),
  ('stairs', 'seasonal', 2, 'Wash the stairwell walls'),
  ('stairs', 'seasonal', 3, 'Clear cobwebs and clean high fixtures and corners'),
  ('stairs', 'seasonal', 4, 'Polish or treat the wood handrail and treads (if wood)'),
  ('hallways', 'weekly', 1, 'Vacuum or sweep and mop the floor'),
  ('hallways', 'weekly', 2, 'Shake out or vacuum runners and mats'),
  ('hallways', 'weekly', 3, 'Dust the console / entry table and surfaces'),
  ('hallways', 'weekly', 4, 'Disinfect doorknobs and light switches'),
  ('hallways', 'weekly', 5, 'Tidy coat hooks and the entry area'),
  ('hallways', 'weekly', 6, 'Empty the entry trash if present'),
  ('hallways', 'monthly', 1, 'Dust baseboards trim and vents'),
  ('hallways', 'monthly', 2, 'Spot-clean walls scuffs and fingerprints'),
  ('hallways', 'monthly', 3, 'Dust wall art mirrors and photos'),
  ('hallways', 'monthly', 4, 'Wipe interior doors and frames'),
  ('hallways', 'monthly', 5, 'Clear ceiling-corner cobwebs'),
  ('hallways', 'monthly', 6, 'Clean light fixtures (reachable)'),
  ('hallways', 'seasonal', 1, 'Wash walls and doors thoroughly'),
  ('hallways', 'seasonal', 2, 'Deep clean floor edges and grout'),
  ('hallways', 'seasonal', 3, 'Clean or launder entry rugs and mats'),
  ('hallways', 'seasonal', 4, 'Clean high fixtures and vents'),
  ('hallways', 'seasonal', 5, 'Wipe down coat / utility closet interiors');
